### ISSUE TITLE
Specified center is not accurately the center of the tile at origin

### ISSUE THREAD

**Issue by kasarol** [datagovsg/hextile#2]
When specifying the center for hextile conversion, I would expect the specified center coordinate to be the center of the first produced hexagon (e.g. grid origin). This is useful when aligning multiple hextiled polygons.

However, even in the module documentation's example usage of center parameter, _center: [103.8, 60]_ produces an origin hexagon centered at _[103.8470918851487,1.3147367663544147]_, which is annoyingly just slightly off the specified point.

**Comment by yongjun21** [comment]
That is not really a bug. There will always be a distortion when you project a spherical surface onto a flat surface: one degree longitude converted to metres will be very different depending on how far away you are from the equator. 

I presume you are testing with the Singapore polygon. With your parameter setting, the origin hexagon (id: "0.0") will indeed be centered at (103.8, 60). However, you will not find this "origin hexagon" inside your output because it lies entirely outside your Singapore polygon bounding box. You should set a center nearer to your polygon bbox to avoid the distortion. The example given in the documentation is specifically chosen to illustrate the distortion effect and is not supposed to be followed. 

I will update the documentation to explained this better.

**Comment by kasarol** [comment]
I am able to accomplish what I was doing by using the same center input for different polygons (as opposed to using the computed center of the origin hexagon), so this is fine. Thank you for clarification.
